channels:
- https://packages.qiime2.org/qiime2/2025.4/amplicon/released
- conda-forge
- bioconda
dependencies:
  - qiime2-amplicon
  - nodejs
  - pip
  - entrezpy
  - python-dotenv
  - pandas
  - pyzotero
  - numpy
  - xmltodict
  - pip:
    - q2doc@git+https://github.com/qiime2/q2doc@dev
    - jupyter-book>=2.0.0a1
    - q2-fondue@git+https://github.com/bokulich-lab/q2-fondue@2025.4.0
